### ISSUE TITLE
Translate to spanish

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-android-inventory-agent#14]
Translate files to Spanish the files on:

res/value-es:

* strings_pref_accueil.xml
* strings_pref_global.xml
* strings_pref_inventory.xml
* strings.xml
* value_time.xml

**Comment by ajsb85** [comment]
Related to: https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/4
