### ISSUE TITLE
Software list in inventory incomplete

### ISSUE THREAD

**Issue by btry** [flyve-mdm/flyve-mdm-android-inventory-agent#41]
Hi, @rafaelje 

On a sony Z2 running CM 12.1 only Android 5.1.1 is reported in the software list. All other stock or additional apps are missing.

Thanks.

**Comment by ajsb85** [comment]
Hi, @btry 
Could you provide the XML generated?
Thanks.

**Comment by btry** [comment]
The latest XML is downloadable from dev server instance. Find the computer, open the tab **Import information** click the download inventory file link. 

![image](https://user-images.githubusercontent.com/14139801/31216332-8b18de82-a9b3-11e7-9d3a-cba2f18f70f8.png)

**Comment by ajsb85** [comment]
Hi, @btry 

I can see the OS and the list of apps in the computer 44
https://dev.flyve.org/glpi/front/computer.form.php?id=44

[Computer-44.xml.zip](https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/files/1364172/Computer-44.xml.zip)

Where is the list of software missed?

**Comment by g-bougard** [comment]
The same here, only Android version is present.

As seen in inventory XML, for example, the following software is missing:
```
    <SOFTWARE>
      <NAME>com.android.providers.telephony</NAME>
      <NAME>7.0</NAME>
      <FILESIZE>0</FILESIZE>
      <FROM>Android</FROM>
    </SOFTWARE>
```

As [specs will telling](http://fusioninventory.org/documentation/dev/spec/protocol/inventory.html) you, the node should better look like this:
```
    <SOFTWARES>
      <NAME>com.android.providers.telephony</NAME>
      <VERSION>7.0</VERSION>
      <FILESIZE>0</FILESIZE>
      <FROM>Android</FROM>
    </SOFTWARES>
```
1. I changed the second NAME by VERSION
2. I added a `S` to `<SOFTWARES/>` 

I tested editing the XML and importing it again, the software appeared.

Then do you think you can obtain a better NAME then a java class ?

Setting FILESIZE could be removed is set to zero.

`INSTALLDATE` would really nice to have.

`SYSTEM_CATEGORY` would also be really nice.

**Comment by ajsb85** [comment]
@g-bougard Good report, thanks.
Fyi, softwares is used only in French, in English is wrong with the "s" at the end.
Let's add support for "softwares" while the new spec is ready to use with the FI v3

+1 to remove FILESIZE when it's 0, INSTALLDATE and INSTALLDATE 👌🏻

**Comment by ajsb85** [comment]
Hi, @rafaelje 
I think it's already fixed.
Could you confirm?
