### ISSUE TITLE
Wrong category? 

### ISSUE THREAD

**Issue by grego1981** [flyve-mdm/flyve-mdm-android-inventory-agent#42]
The agent works superb for my needs, but mobile phones are inventoried as computers and not phones. Is this by design? Is there a way to inventory them as phones? I use GLPI 9.1.6 and FI.

Thank you!

**Comment by ajsb85** [comment]
@grego1981 Hi! 

Many categories for phones:

* Landline telephone 
* VoIP phones
* Feature phones
* SmartPhones
* Mobile Devices (SmartPhones, Tablets...)

Our inventory agents is designed to support mobile devices, desktops and SmartTVs, or any computer with Android and iOS.

References:
https://github.com/fusioninventory/fusioninventory.github.io/issues/26#issuecomment-319476308

**Comment by grego1981** [comment]
Thanks for the reply! Now it's clear, maybe a new category "smart devices", as a hybrid between phones and computers, would make more sense.

**Comment by ajsb85** [comment]
@grego1981 FI may support new categories (you can read in the reference link), but for me computer is the proper category. And assign to type of computer: smartphone.

**Comment by rafaelje** [comment]
Hi @grego1981 I think we can close this issue, feel free to open again if you need more info

**Comment by ajsb85** [comment]
Hi, @ticgal.

Here the answer about linking computers and not phones.

Best regards.

**Comment by TICgal** [comment]
Makes sense as we can link the new SIM cards to computers in GLPi 9.2 ;)
Thanks
