### ISSUE TITLE
New strings for the UI

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-inventory-agent#53]
Hi, @rafaelje 

Please update these new strings in the Application.
Check if CircleCI upload the new strings to Transifex.

Thanks.

# Inventory Agent Settings

### Inventory

Disable/Enable inventory

### Run inventory now

Send inventory report

### Inventory parameters

Schedule the inventory task 

### Global settings

Setup credentials, server...

### About

License and build information

### Help

Articles of the help center

# Global settings

### Boot options

Startup from system boot

### Notifications

Disable/Enable toast notifications

### Server adress

Define server address

### Tag

Custom asset tag

### Health Report 

Send crash reports 

### Usage Data

Send anonymous usage data

# Inventory parameters

### Automatic inventory

Disable/Enable automatic inventory

### Frequency

Define frequency

# Frequency

* Day
* Week
* Month

**Comment by rafaelje** [comment]
In transifex we have translate just one file string.xml but the other 5 files was not translate to prevent this happend again I unify all the language file in one

**Comment by ajsb85** [comment]
@rafaelje Very good. 
Thanks

**Comment by rafaelje** [comment]
This is the new route map

<img width="972" alt="captura de pantalla 2017-09-29 a las 11 15 32 a m" src="https://user-images.githubusercontent.com/4085091/31022683-92d5b984-a507-11e7-8df9-8670b42d0efc.png">
