### ISSUE TITLE
Rename app

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-inventory-agent#54]
Hi, @rafaelje 

Please, remove the word "Agent" in the product icon in the screen.
Keep only the name: "Inventory Agent"  for the name of the service.

**Comment by rafaelje** [comment]
![screenshot_1506695726](https://user-images.githubusercontent.com/4085091/31021551-27a106ee-a504-11e7-87a1-9ca366c00c73.png)

Will be available in the next beta release

**Comment by ajsb85** [comment]
![imagen](https://user-images.githubusercontent.com/663460/31103332-9d29e276-a7d6-11e7-9a6a-7f7e74c5d8a6.png)
