### ISSUE TITLE
Wrong label on Usage Data checkbox

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-inventory-agent#61]
Hi, @rafaelje 

When I check the item, dynamically add a wrong label "Send crash report"

![imagen](https://user-images.githubusercontent.com/663460/31101272-37c60f58-a7cd-11e7-92e5-04ea3c038802.png)

![imagen](https://user-images.githubusercontent.com/663460/31101276-3aa2381e-a7cd-11e7-81d2-c2d51734574f.png)

**Comment by rafaelje** [comment]
@ajsb85 fix on the next PR

**Comment by rafaelje** [comment]
close in this PR https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/pull/62
