### ISSUE TITLE
Commit link in the about page return status 404

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-inventory-agent#63]
Hi, @rafaelje 

The link return 404 on GitHub.
And the link cover from the start of the commit ID and finish after the copyright symbol.

**Comment by ajsb85** [comment]
![imagen](https://user-images.githubusercontent.com/663460/31103364-d7f4c40c-a7d6-11e7-865b-efbe44b262cd.png)

**Comment by rafaelje** [comment]
Fix the html open tag and now look good, will be available on the next PR

![screenshot_1507039125](https://user-images.githubusercontent.com/4085091/31129048-7bc0e4a4-a821-11e7-8dc2-21af93d3fc75.png)
