### ISSUE TITLE
Build for Android-x86 7.1-rc1 (Nougat-x86)

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-inventory-agent#76]
Hi, @rafaelje 

Could you prepare the build on CircleCI for x86?
It's was in progress for Oreo?

Reference:
http://www.android-x86.org/releases/releasenote-7-1-rc1

**Comment by rafaelje** [comment]
Hi @ajsb85 

To run it requires hardware acceleration and I'm finding if we can walk through it on CircleCI VM

<img width="620" alt="captura de pantalla 2017-10-09 a las 4 23 56 p m" src="https://user-images.githubusercontent.com/4085091/31357183-adc2b9b8-ad0e-11e7-8e47-37d61c8b7713.png">

**Comment by rafaelje** [comment]
At this point CircleCI does not support KVM and can't run x86 emulation

<img width="624" alt="captura de pantalla 2017-10-09 a las 4 49 25 p m" src="https://user-images.githubusercontent.com/4085091/31357983-d55e3e2c-ad11-11e7-8117-3cbafcf0253d.png">

**Comment by ajsb85** [comment]
Ok, look this solution.
https://discuss.circleci.com/t/x86-android-emulators/16433/2

**Comment by g-bougard** [comment]
Last build 885 worked on my T102HA with Android-x86 7.1-rc1
