### ISSUE TITLE
Unable to start activity in x86

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-inventory-agent#79]
Hi, @rafaelje 

@g-bougard reported to us a bug with Android-x86 7.1-rc1 (Nougat-x86)  

`nullPointerException in MainActivity.java in the onCreate method.`

No crash report sent to the @thestralbot nor Google Play console.

Reference:  https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/76

**Comment by ajsb85** [comment]
Bug reported by @thestralbot

Device ASUSTeK COMPUTER INC. T102HA OS 7.1.2

```Console
Unable to start activity ComponentInfo{org.flyve.inventory.agent/org.flyve.inventory.agent.MainActivity}: 

java.lang.NullPointerException: 

Attempt to invoke virtual method 'void android.support.v7.widget.Toolbar.setTitle(java.lang.CharSequence)' on a null object reference
````

**Comment by g-bougard** [comment]
This is fixed for me after update with build 885.
