### ISSUE TITLE
URIError: URI malformed - Anonymous Report 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-android-inventory-agent#86]
Hi, @rafaelje 

I can send the payload with Postman to the backend and it's works.
But from the agent does not works.

Here the documentation about the error message:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Malformed_URI

Best regards.

**Comment by rafaelje** [comment]
@ajsb85 This error is sending to Fusion Inventory Plugin or other?

**Comment by ajsb85** [comment]
When you send the payload to the @chollimabot

**Comment by ajsb85** [comment]
Hi, @rafaelje 

I debugged today the webhook platform for @chollimabot 

You are sending the `content-type` as `application/x-www-form-urlencoded` instead `application/json`
